// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICnlOjNcZboibNJGD0TVR-c92vwEUC-Q',
    appId: '1:181595610510:web:7aee109c498a349de118df',
    messagingSenderId: '181595610510',
    projectId: 'modmate-database',
    authDomain: 'modmate-database.firebaseapp.com',
    storageBucket: 'modmate-database.firebasestorage.app',
    measurementId: 'G-T6BE0WWCYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgd2np_LZiyqPk3qgtU7oTH3Wwxer-C2c',
    appId: '1:181595610510:android:6b990ab1b94aad1ae118df',
    messagingSenderId: '181595610510',
    projectId: 'modmate-database',
    storageBucket: 'modmate-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrF4XPOpQRQnQLEU0l3DnP5eFwj_zdgKA',
    appId: '1:181595610510:ios:436385614da43f60e118df',
    messagingSenderId: '181595610510',
    projectId: 'modmate-database',
    storageBucket: 'modmate-database.firebasestorage.app',
    iosBundleId: 'com.example.modmateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrF4XPOpQRQnQLEU0l3DnP5eFwj_zdgKA',
    appId: '1:181595610510:ios:436385614da43f60e118df',
    messagingSenderId: '181595610510',
    projectId: 'modmate-database',
    storageBucket: 'modmate-database.firebasestorage.app',
    iosBundleId: 'com.example.modmateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICnlOjNcZboibNJGD0TVR-c92vwEUC-Q',
    appId: '1:181595610510:web:fe94a4ae2f547b87e118df',
    messagingSenderId: '181595610510',
    projectId: 'modmate-database',
    authDomain: 'modmate-database.firebaseapp.com',
    storageBucket: 'modmate-database.firebasestorage.app',
    measurementId: 'G-P01ZYJX8TG',
  );
}
